CREATE TABLE  "PERSON" 
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(45), 
	"LAST_NAME" VARCHAR2(45), 
	"EMAIL" VARCHAR2(45), 
	"PHONE_NUMBER" VARCHAR2(45), 
	 PRIMARY KEY ("ID") ENABLE
   ) ;
   
CREATE SEQUENCE "PERSON_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;